# AWS CodeBuild Spec
# https://docs.aws.amazon.com/ja_jp/codebuild/latest/userguide/batch-build-buildspec.html
version: 0.2

env:
  variables:
    LOG_LEVEL: "info"
  ## AWS ParameterStore
  # parameter-store:
  #   SOME_KEY: /SOME/PARAM/PATH
  ## AWS Secrets Manager
  secrets-manager:
    DOCKERHUB_USER: arn:aws:secretsmanager:${AWS_REGION}:${AWS_ACCOUNT_ID}:secret:${AWS_KMS_ID}:username
    DOCKERHUB_PASS: arn:aws:secretsmanager:${AWS_REGION}:${AWS_ACCOUNT_ID}:secret:${AWS_KMS_ID}:password

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Begin AWS CodeBuild Process, BuildID=${CODEBUILD_BUILD_ID} .
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_REGION --no-include-email)
      # Gets commit front 7 chars of the git commit hash value.
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
    on-failure:
      - echo Pre Build Phase has Failed.
  build:
    commands:
      - echo Build started on `date`
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
      - echo Building the Docker image...
      - AWS_ACCOUNT_ID=$(echo $CODEBUILD_BUILD_ARN | cut -f 5 -d :)
      - docker build -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${APP_NAME}:${IMAGE_TAG} .
      - docker tag ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${APP_NAME}:${IMAGE_TAG} ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${APP_NAME}:latest
    on-failure:
      - echo Build Phase has Failed.
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - AWS_ACCOUNT_ID=$(echo $CODEBUILD_BUILD_ARN | cut -f 5 -d :)
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${APP_NAME}:latest
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${APP_NAME}:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"{APP_NAME}","imageUri":"%s"}]' ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${APP_NAME}:${IMAGE_TAG} > imagedefinitions.json
    on-failure:
      - echo Post Build Phase has Failed.
artifacts:
  files:
    - imagedefinitions.json
